In [5]:
# API endpoint tests
import pandas as pd
from nba_api.stats.endpoints import leaguegamelog

In [9]:
# Get team game logs for a specific season:
def get_team_game_logs(season: str, season_type: str = "Regular Season") -> pd.DataFrame:
    gamelog = leaguegamelog.LeagueGameLog(
        season=season,
        season_type_all_star=season_type,
        player_or_team_abbreviation="T"   # "T" for team logs, "P" for player logs
    )
    df = gamelog.get_data_frames()[0]
    return df

In [10]:
get_team_game_logs("2024-25")

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22024,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,240,48,...,29,40,33,6,3,4,15,132,23,1
1,22024,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,240,35,...,35,47,17,4,1,16,22,103,-7,1
2,22024,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,240,42,...,31,46,22,7,8,7,22,110,7,1
3,22024,1610612752,NYK,New York Knicks,0022400061,2024-10-22,NYK @ BOS,L,240,43,...,29,34,20,2,3,12,12,109,-23,1
4,22024,1610612744,GSW,Golden State Warriors,0022400072,2024-10-23,GSW @ POR,W,240,48,...,42,57,38,13,5,18,27,140,36,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22024,1610612747,LAL,Los Angeles Lakers,0022401199,2025-04-13,LAL @ POR,L,240,31,...,29,42,21,9,11,21,21,81,-28,1
2456,22024,1610612759,SAS,San Antonio Spurs,0022401197,2025-04-13,SAS vs. TOR,W,240,43,...,41,50,22,11,2,12,13,125,7,1
2457,22024,1610612763,MEM,Memphis Grizzlies,0022401194,2025-04-13,MEM vs. DAL,W,240,52,...,34,53,31,13,7,12,15,132,35,1
2458,22024,1610612738,BOS,Boston Celtics,0022401187,2025-04-13,BOS vs. CHA,W,240,35,...,34,49,22,12,6,13,14,93,7,1
2459,22024,1610612756,PHX,Phoenix Suns,0022401200,2025-04-13,PHX @ SAC,L,240,40,...,28,37,28,6,1,13,9,98,-11,1

In [12]:
# get player logs for a specific season:
def get_player_game_logs(season: str, season_type: str = "Regular Season") -> pd.DataFrame:
    gamelog = leaguegamelog.LeagueGameLog(
        season=season,
        season_type_all_star=season_type,
        player_or_team_abbreviation="P"   # "T" for team logs, "P" for player logs
    )
    df = gamelog.get_data_frames()[0]
    return df

In [13]:
get_player_game_logs("2024-25")

,SEASON_ID,PLAYER_ID,PLAYER_NAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,...,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,FANTASY_PTS,VIDEO_AVAILABLE
0,22024,201143,Al Horford,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,...,3,5,1,1,0,2,11,19,28.1,1
1,22024,201950,Jrue Holiday,1610612738,BOS,Boston Celtics,0022400061,2024-10-22,BOS vs. NYK,W,...,4,4,1,0,0,2,18,23,31.8,1
2,22024,2544,LeBron James,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,...,5,4,0,2,2,3,16,-6,32.0,1
3,22024,1630559,Austin Reaves,1610612747,LAL,Los Angeles Lakers,0022400062,2024-10-22,LAL vs. MIN,W,...,9,4,1,1,0,4,12,12,34.8,1
4,22024,201144,Mike Conley,1610612750,MIN,Minnesota Timberwolves,0022400062,2024-10-22,MIN @ LAL,L,...,4,2,1,0,3,1,5,-22,12.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26301,22024,1629162,Jordan McLaughlin,1610612759,SAS,San Antonio Spurs,0022401197,2025-04-13,SAS vs. TOR,W,...,0,0,0,0,0,1,2,0,2.0,1
26302,22024,1642264,Stephon Castle,1610612759,SAS,San Antonio Spurs,0022401197,2025-04-13,SAS vs. TOR,W,...,8,6,0,0,4,2,20,2,34.6,1
26303,22024,1631119,Jaylin Williams,1610612760,OKC,Oklahoma City Thunder,0022401196,2025-04-13,OKC @ NOP,W,...,2,0,0,0,0,0,0,9,2.4,1
26304,22024,1642382,Branden Carlson,1610612760,OKC,Oklahoma City Thunder,0022401196,2025-04-13,OKC @ NOP,W,...,10,2,0,3,2,3,26,8,48.0,1
26305,22024,1630194,Paul Reed,1610612765,DET,Detroit Pistons,0022401192,2025-04-13,DET @ MIL,L,...,6,5,0,1,1,3,8,0,24.7,1